### PR TITLE
Daniel Lara & Roy Tan

### PR DESCRIPTION
**Pull request by Dan-Lara**
- [x] GET /posts
When the client makes a `GET` request to `/posts`:
    - If the client provides the query-string parameter `term`, filter the posts to those that have the `term` in their `title` or `contents` (or both), and send down those posts in a JSON response.
    - Otherwise, send down the full array of posts as a JSON response.

- [x] POST /posts
    - When the client makes a `POST` request to `/posts`:
        - Ensure that the client provides both `title` and `contents` in the request body. If any of these don't exist, send an object of the form `{ error: "Error message" }` as a JSON response. Make sure to respond with an appropriate status code.
        - If all fields are provided, create a new post object. Assign the post a unique, numeric `id` property that will act as its identifier, and add it to the posts array. Return the newly created post object, with its assigned `id`, to the client in a JSON response.

- [x] PUT /posts
    - When the client makes a `PUT` request to `/posts`:
        - Ensure that the client provides `id`, `title`, and `contents` in the request body. If any of these don't exist, send an object of the form `{ error: "Error message" }` as a JSON response. Make sure to respond with an appropriate status code.
        - If the `id` doesn't correspond to a valid post, respond with an error in the same form as above.
        - Modify the post with the given `id`, updating its `title` and `contents`.  Respond with the newly updated post object in a JSON response.

- [x] DELETE /posts
    - When the client makes a `DELETE` request to `/posts`:
        - Ensure that the client provides an `id` in the request body, and that the `id` corresponds to a valid post. If there's an error, send an object of the form `{ error: "Error message" }` as a JSON response. Make sure to respond with an appropriate status code.
        - Remove the post with the given `id` from the array of posts. Return the object `{ success: true }` in a JSON response.

### CODE REVIEW

**Comment by mixelpixel** [comment]
Absolutely :heart: your use of the Task List syntax :smiley_cat: 

I cloned your repo and ran the tests... got this:

```
C:\Users\patrick\TA\daniel\Node-Express-Lab\src\server.js
   30:3   warning  Unexpected console statement                                               no-console
   76:11  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   77:11  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   99:11  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  100:11  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  101:11  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  126:13  error    Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins

â 7 problems (6 errors, 1 warning)

npm ERR! Test failed.  See above for more details.
```

I suspect the "errors" are just Linter complaints...

I'm gonna stick a little magic in your script to make them go away and will see if that makes `npm test` happy...

**Comment by mixelpixel** [comment]
:thinking: 
Well, i was expecting to see "no-prototype-builtins" specified in the eslintrs.json file... but! putting this
```
/* eslint no-prototype-builtins: 0 */
```

In your src/server.js file makes the no-pro-builtin a non-issue... :stuck_out_tongue:

**Comment by mixelpixel** [comment]
Oh nice - check it out, I edited your first comment and now the "status bar" shows up in the main PR list:

capture

**Comment by Dan-Lara** [comment]
Awesome, thanks!

**Pull request closed without merging**
